name: Build and Test APIDiff

on:
  push:
    branches-ignore:
      - master
      - pr/*

jobs:

  linux-x64:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1

      - name: 'Set up Java Development Kit'
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'oracle'
          java-version: 21

      - name: 'Build APIDiff'
        shell: bash
        run: bash make/build.sh

      - name: 'Self-test APIDiff'
        shell: bash
        run: bash make/build.sh --skip-download -- test
